version: "3"
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vite_remix
    ports:
      - "5432:5432"
    volumes:
      - vite-remix-postgres:/var/lib/postgresql/data

volumes:
  vite-remix-postgres:
    external: false
